In [2]:
import pandas as pd

In [3]:
df_1 = pd.read_excel('수질TMS 1월 data.xlsx', header=None)
df_2 = pd.read_excel('수질TMS 2월 data.xlsx', header=None)
df_3 = pd.read_excel('수질TMS 3월 data.xlsx', header=None)
df_4 = pd.read_excel('수질TMS 4월 data.xlsx', header=None)
df_5 = pd.read_excel('수질TMS 5월 data.xlsx', header=None)
df_6 = pd.read_excel('수질TMS 6월 data.xlsx', header=None)

C:\Users\inthe\anaconda3\envs\ribeco\lib\site-packages\openpyxl\styles\stylesheet.py:221: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [4]:
df_1.drop([0,1,2])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
3,1,2021/01/01,00시00분,40,19.0,장비정상,10,7.2,장비정상,20,18.217,장비정상,0.5,0.112,장비정상,8.6,6.9,장비정상
4,1,2021/01/01,00시05분,40,19.0,장비정상,10,7.1,장비정상,20,18.217,장비정상,0.5,0.112,장비정상,8.6,6.9,장비정상
5,1,2021/01/01,00시10분,40,19.0,장비정상,10,6.9,장비정상,20,18.217,장비정상,0.5,0.112,장비정상,8.6,6.8,장비정상
6,1,2021/01/01,00시15분,40,19.0,장비정상,10,6.9,장비정상,20,18.217,장비정상,0.5,0.112,장비정상,8.6,6.8,장비정상
7,1,2021/01/01,00시20분,40,19.0,장비정상,10,6.9,장비정상,20,18.217,장비정상,0.5,0.112,장비정상,8.6,6.8,장비정상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8926,1,2021/01/31,23시35분,40,-0.6,장비정상,10,8.7,장비정상,20,19.663,장비정상,0.5,0.000,장비정상,8.6,6.9,장비정상
8927,1,2021/01/31,23시40분,40,-0.6,장비정상,10,8.7,장비정상,20,19.663,장비정상,0.5,0.000,장비정상,8.6,6.9,장비정상
8928,1,2021/01/31,23시45분,40,-0.6,장비정상,10,8.6,장비정상,20,19.663,장비정상,0.5,0.000,장비정상,8.6,6.9,장비정상
8929,1,2021/01/31,23시50분,40,-0.6,장비정상,10,8.5,장비정상,20,17.907,장비정상,0.5,0.000,장비정상,8.6,6.9,장비정상
8930,1,2021/01/31,23시55분,40,60.9,장비정상,10,8.5,장비정상,20,17.154,장비정상,0.5,0.000,장비정상,8.6,6.9,장비정상

In [5]:
# 컬럼명 재정의 하기
df_1 = df_1.drop([0,1,2])
columns =  ['방류구','측정일자',	'측정시간',	'COD_기준치', 'COD_측정치',	'COD_상태정보',	'SS_기준치',	'SS_측정치',	'SS_상태정보',	'T-N_기준치'	,'T-N_측정치',	'T-N_상태정보',	'T-P_기준치',	'T-P_측정치','T-P_상태정보',	'pH_기준치'	,'PH_측정치', 'PH_상태정보']
df_1.columns = columns
df_1.sample()

,방류구,측정일자,측정시간,COD_기준치,COD_측정치,COD_상태정보,SS_기준치,SS_측정치,SS_상태정보,T-N_기준치,T-N_측정치,T-N_상태정보,T-P_기준치,T-P_측정치,T-P_상태정보,pH_기준치,PH_측정치,PH_상태정보
2015,1,2021/01/07,23시40분,40,19.2,장비정상,10,5.7,장비정상,20,15.198,장비정상,0.5,0.215,장비정상,8.6,7.1,장비정상

In [6]:
df_2 = df_2.drop([0,1,2])
df_3 = df_3.drop([0,1,2])
df_4 = df_4.drop([0,1,2])
df_5 = df_5.drop([0,1,2])
df_6 = df_6.drop([0,1,2])

In [7]:
df_2.columns = columns
df_3.columns = columns
df_4.columns = columns
df_5.columns = columns
df_6.columns = columns

In [8]:
data = pd.concat([df_1,df_2,df_3,df_4,df_5,df_6], ignore_index=True)

In [9]:
data[data['COD_상태정보'] == '미수신']
# 미수신 데이터 2건 존재

,방류구,측정일자,측정시간,COD_기준치,COD_측정치,COD_상태정보,SS_기준치,SS_측정치,SS_상태정보,T-N_기준치,T-N_측정치,T-N_상태정보,T-P_기준치,T-P_측정치,T-P_상태정보,pH_기준치,PH_측정치,PH_상태정보
25949,1,2021/04/01,02시25분,40,-,미수신,10,-,미수신,20,-,미수신,0.5,-,미수신,8.6,-,미수신
52038,1,2021/06/30,16시30분,40,-,미수신,10,-,미수신,20,-,미수신,0.5,-,미수신,8.6,-,미수신

In [10]:
data_origin = data.copy()

In [11]:
data_not_received = data[data['COD_상태정보']!= '미수신']

In [12]:
data_not_received

,방류구,측정일자,측정시간,COD_기준치,COD_측정치,COD_상태정보,SS_기준치,SS_측정치,SS_상태정보,T-N_기준치,T-N_측정치,T-N_상태정보,T-P_기준치,T-P_측정치,T-P_상태정보,pH_기준치,PH_측정치,PH_상태정보
0,1,2021/01/01,00시00분,40,19.0,장비정상,10,7.2,장비정상,20,18.217,장비정상,0.5,0.112,장비정상,8.6,6.9,장비정상
1,1,2021/01/01,00시05분,40,19.0,장비정상,10,7.1,장비정상,20,18.217,장비정상,0.5,0.112,장비정상,8.6,6.9,장비정상
2,1,2021/01/01,00시10분,40,19.0,장비정상,10,6.9,장비정상,20,18.217,장비정상,0.5,0.112,장비정상,8.6,6.8,장비정상
3,1,2021/01/01,00시15분,40,19.0,장비정상,10,6.9,장비정상,20,18.217,장비정상,0.5,0.112,장비정상,8.6,6.8,장비정상
4,1,2021/01/01,00시20분,40,19.0,장비정상,10,6.9,장비정상,20,18.217,장비정상,0.5,0.112,장비정상,8.6,6.8,장비정상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52033,1,2021/06/30,16시05분,40,14.2,장비정상,10,2.3,장비정상,20,14.935,장비정상,0.5,0.091,장비정상,8.6,6.4,장비정상
52034,1,2021/06/30,16시10분,40,14.2,장비정상,10,2.3,장비정상,20,14.935,장비정상,0.5,0.091,장비정상,8.6,6.4,장비정상
52035,1,2021/06/30,16시15분,40,14.2,장비정상,10,2.2,장비정상,20,14.935,장비정상,0.5,0.091,장비정상,8.6,6.4,장비정상
52036,1,2021/06/30,16시20분,40,14.2,장비정상,10,2.1,장비정상,20,14.935,장비정상,0.5,0.091,장비정상,8.6,6.4,장비정상
52037,1,2021/06/30,16시25분,40,14.2,장비정상,10,2.4,장비정상,20,14.935,장비정상,0.5,0.091,장비정상,8.6,6.4,장비정상

In [13]:
astype_data = data_not_received.astype({'COD_측정치':float,'SS_측정치':float,'T-N_측정치':float, 'T-P_측정치':float, 'T-N_측정치':float, 'PH_측정치':float})

# 시계역 데이터 전처리 과정
 1. string to datetime
 2. Frequency 설정
 3. 시계열 데이터 요소 추출(count_trend, count,seasonal)
 4. rolling() (Count_day, count_week)
 5. 그룹화(temp_group)

In [14]:
astype_data['측정시간'] =astype_data['측정일자'] +' '+ astype_data['측정시간']

In [15]:
astype_data['측정시간'] = astype_data['측정시간'].apply(lambda x: x.replace('시',':'))
astype_data['측정시간'] = astype_data['측정시간'].apply(lambda x: x.replace('분',''))

In [16]:
astype_data['측정시간'] = pd.to_datetime(astype_data['측정시간'])

In [17]:
astype_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52037 entries, 0 to 52037
Data columns (total 18 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   방류구       52037 non-null  object
 1   측정일자      52037 non-null  object
 2   측정시간      52037 non-null  datetime64[ns]
 3   COD_기준치   52037 non-null  object
 4   COD_측정치   52037 non-null  float64
 5   COD_상태정보  52037 non-null  object
 6   SS_기준치    52037 non-null  object
 7   SS_측정치    52037 non-null  float64
 8   SS_상태정보   52037 non-null  object
 9   T-N_기준치   52037 non-null  object
 10  T-N_측정치   52037 non-null  float64
 11  T-N_상태정보  52037 non-null  object
 12  T-P_기준치   52037 non-null  object
 13  T-P_측정치   52037 non-null  float64
 14  T-P_상태정보  52037 non-null  object
 15  pH_기준치    52037 non-null  object
 16  PH_측정치    52037 non-null  float64
 17  PH_상태정보   52037 non-null  object
dtypes: datetime64[ns](1), float64(5), object(12)
memory usage: 7.5+ MB

In [18]:
astype_data.to_csv('Analysis_data.csv', encoding = 'utf-8',index =False)

### 장비 상태가 '장비정상'이 나오지 않으면 해당 측정시간 리스트에 저장하고 정상데이터 나온것까지 시계열 패턴분석

In [47]:
data = astype_data.copy()

In [42]:
# 함수만들기
# 데이터프레임안의 측정시간을 리스트로 저장
measure_time_list_save = list(astype_data['측정시간'])

In [72]:
# 함수만들기
# 5개의 상태정보 중 장비정상이 아닌 값을 만나면 해당 날짜 리스트에 저장하는 함수
# for measure_time in measure_time_list_save:
#     part_data = data[data['측정시간'] == measure_time]
#     error_measure_time_list = []
#     print(part_data['COD_상태정보'])
print(1)

1

In [1]:
for i in range(len(data)):
    status_list = data.loc[i,['COD_상태정보','SS_상태정보','T-N_상태정보','T-P_상태정보','PH_상태정보']]
    if status_list !='장비정상':
        print(status_list)

NameError: name 'data' is not defined